# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analyzer.proto

require 'google/protobuf'

require 'plugin_pb'
require 'google/protobuf/empty_pb'
require 'google/protobuf/struct_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("analyzer.proto", :syntax => :proto3) do
    add_message "pulumirpc.AnalyzeRequest" do
      optional :type, :string, 1
      optional :properties, :message, 2, "google.protobuf.Struct"
      optional :urn, :string, 3
      optional :name, :string, 4
      optional :options, :message, 5, "pulumirpc.AnalyzerResourceOptions"
      optional :provider, :message, 6, "pulumirpc.AnalyzerProviderResource"
    end
    add_message "pulumirpc.AnalyzerResource" do
      optional :type, :string, 1
      optional :properties, :message, 2, "google.protobuf.Struct"
      optional :urn, :string, 3
      optional :name, :string, 4
      optional :options, :message, 5, "pulumirpc.AnalyzerResourceOptions"
      optional :provider, :message, 6, "pulumirpc.AnalyzerProviderResource"
      optional :parent, :string, 7
      repeated :dependencies, :string, 8
      map :propertyDependencies, :string, :message, 9, "pulumirpc.AnalyzerPropertyDependencies"
    end
    add_message "pulumirpc.AnalyzerResourceOptions" do
      optional :protect, :bool, 1
      repeated :ignoreChanges, :string, 2
      optional :deleteBeforeReplace, :bool, 3
      optional :deleteBeforeReplaceDefined, :bool, 4
      repeated :additionalSecretOutputs, :string, 5
      repeated :aliases, :string, 6
      optional :customTimeouts, :message, 7, "pulumirpc.AnalyzerResourceOptions.CustomTimeouts"
    end
    add_message "pulumirpc.AnalyzerResourceOptions.CustomTimeouts" do
      optional :create, :double, 1
      optional :update, :double, 2
      optional :delete, :double, 3
    end
    add_message "pulumirpc.AnalyzerProviderResource" do
      optional :type, :string, 1
      optional :properties, :message, 2, "google.protobuf.Struct"
      optional :urn, :string, 3
      optional :name, :string, 4
    end
    add_message "pulumirpc.AnalyzerPropertyDependencies" do
      repeated :urns, :string, 1
    end
    add_message "pulumirpc.AnalyzeStackRequest" do
      repeated :resources, :message, 1, "pulumirpc.AnalyzerResource"
    end
    add_message "pulumirpc.AnalyzeResponse" do
      repeated :diagnostics, :message, 2, "pulumirpc.AnalyzeDiagnostic"
    end
    add_message "pulumirpc.AnalyzeDiagnostic" do
      optional :policyName, :string, 1
      optional :policyPackName, :string, 2
      optional :policyPackVersion, :string, 3
      optional :description, :string, 4
      optional :message, :string, 5
      repeated :tags, :string, 6
      optional :enforcementLevel, :enum, 7, "pulumirpc.EnforcementLevel"
      optional :urn, :string, 8
    end
    add_message "pulumirpc.AnalyzerInfo" do
      optional :name, :string, 1
      optional :displayName, :string, 2
      repeated :policies, :message, 3, "pulumirpc.PolicyInfo"
      optional :version, :string, 4
      optional :supportsConfig, :bool, 5
      map :initialConfig, :string, :message, 6, "pulumirpc.PolicyConfig"
    end
    add_message "pulumirpc.PolicyInfo" do
      optional :name, :string, 1
      optional :displayName, :string, 2
      optional :description, :string, 3
      optional :message, :string, 4
      optional :enforcementLevel, :enum, 5, "pulumirpc.EnforcementLevel"
      optional :configSchema, :message, 6, "pulumirpc.PolicyConfigSchema"
    end
    add_message "pulumirpc.PolicyConfigSchema" do
      optional :properties, :message, 1, "google.protobuf.Struct"
      repeated :required, :string, 2
    end
    add_message "pulumirpc.PolicyConfig" do
      optional :enforcementLevel, :enum, 1, "pulumirpc.EnforcementLevel"
      optional :properties, :message, 2, "google.protobuf.Struct"
    end
    add_message "pulumirpc.ConfigureAnalyzerRequest" do
      map :policyConfig, :string, :message, 1, "pulumirpc.PolicyConfig"
    end
    add_enum "pulumirpc.EnforcementLevel" do
      value :ADVISORY, 0
      value :MANDATORY, 1
      value :DISABLED, 2
    end
  end
end

module Pulumirpc
  AnalyzeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.AnalyzeRequest").msgclass
  AnalyzerResource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.AnalyzerResource").msgclass
  AnalyzerResourceOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.AnalyzerResourceOptions").msgclass
  AnalyzerResourceOptions::CustomTimeouts = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.AnalyzerResourceOptions.CustomTimeouts").msgclass
  AnalyzerProviderResource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.AnalyzerProviderResource").msgclass
  AnalyzerPropertyDependencies = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.AnalyzerPropertyDependencies").msgclass
  AnalyzeStackRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.AnalyzeStackRequest").msgclass
  AnalyzeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.AnalyzeResponse").msgclass
  AnalyzeDiagnostic = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.AnalyzeDiagnostic").msgclass
  AnalyzerInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.AnalyzerInfo").msgclass
  PolicyInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.PolicyInfo").msgclass
  PolicyConfigSchema = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.PolicyConfigSchema").msgclass
  PolicyConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.PolicyConfig").msgclass
  ConfigureAnalyzerRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.ConfigureAnalyzerRequest").msgclass
  EnforcementLevel = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.EnforcementLevel").enummodule
end
