# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: engine.proto for package 'pulumirpc'
# Original file comments:
# Copyright 2016-2018, Pulumi Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'grpc'
require 'engine_pb'

module Pulumirpc
  module Engine
    # Engine is an auxiliary service offered to language and resource provider plugins. Its main purpose today is
    # to serve as a common logging endpoint, but it also serves as a state storage mechanism for language hosts
    # that can't store their own global state.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'pulumirpc.Engine'

      # Log logs a global message in the engine, including errors and warnings.
      rpc :Log, ::Pulumirpc::LogRequest, ::Google::Protobuf::Empty
      # GetRootResource gets the URN of the root resource, the resource that should be the root of all
      # otherwise-unparented resources.
      rpc :GetRootResource, ::Pulumirpc::GetRootResourceRequest, ::Pulumirpc::GetRootResourceResponse
      # SetRootResource sets the URN of the root resource.
      rpc :SetRootResource, ::Pulumirpc::SetRootResourceRequest, ::Pulumirpc::SetRootResourceResponse
    end

    Stub = Service.rpc_stub_class
  end
end
