# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: engine.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("engine.proto", :syntax => :proto3) do
    add_message "pulumirpc.LogRequest" do
      optional :severity, :enum, 1, "pulumirpc.LogSeverity"
      optional :message, :string, 2
      optional :urn, :string, 3
      optional :streamId, :int32, 4
      optional :ephemeral, :bool, 5
    end
    add_message "pulumirpc.GetRootResourceRequest" do
    end
    add_message "pulumirpc.GetRootResourceResponse" do
      optional :urn, :string, 1
    end
    add_message "pulumirpc.SetRootResourceRequest" do
      optional :urn, :string, 1
    end
    add_message "pulumirpc.SetRootResourceResponse" do
    end
    add_enum "pulumirpc.LogSeverity" do
      value :DEBUG, 0
      value :INFO, 1
      value :WARNING, 2
      value :ERROR, 3
    end
  end
end

module Pulumirpc
  LogRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.LogRequest").msgclass
  GetRootResourceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.GetRootResourceRequest").msgclass
  GetRootResourceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.GetRootResourceResponse").msgclass
  SetRootResourceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.SetRootResourceRequest").msgclass
  SetRootResourceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.SetRootResourceResponse").msgclass
  LogSeverity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.LogSeverity").enummodule
end
