# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: errors.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("errors.proto", :syntax => :proto3) do
    add_message "pulumirpc.ErrorCause" do
      optional :message, :string, 1
      optional :stackTrace, :string, 2
    end
  end
end

module Pulumirpc
  ErrorCause = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.ErrorCause").msgclass
end
