# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: language.proto

require 'google/protobuf'

require 'plugin_pb'
require 'google/protobuf/empty_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("language.proto", :syntax => :proto3) do
    add_message "pulumirpc.GetRequiredPluginsRequest" do
      optional :project, :string, 1
      optional :pwd, :string, 2
      optional :program, :string, 3
    end
    add_message "pulumirpc.GetRequiredPluginsResponse" do
      repeated :plugins, :message, 1, "pulumirpc.PluginDependency"
    end
    add_message "pulumirpc.RunRequest" do
      optional :project, :string, 1
      optional :stack, :string, 2
      optional :pwd, :string, 3
      optional :program, :string, 4
      repeated :args, :string, 5
      map :config, :string, :string, 6
      optional :dryRun, :bool, 7
      optional :parallel, :int32, 8
      optional :monitor_address, :string, 9
      optional :queryMode, :bool, 10
      repeated :configSecretKeys, :string, 11
    end
    add_message "pulumirpc.RunResponse" do
      optional :error, :string, 1
      optional :bail, :bool, 2
    end
  end
end

module Pulumirpc
  GetRequiredPluginsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.GetRequiredPluginsRequest").msgclass
  GetRequiredPluginsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.GetRequiredPluginsResponse").msgclass
  RunRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.RunRequest").msgclass
  RunResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.RunResponse").msgclass
end
