# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("plugin.proto", :syntax => :proto3) do
    add_message "pulumirpc.PluginInfo" do
      optional :version, :string, 1
    end
    add_message "pulumirpc.PluginDependency" do
      optional :name, :string, 1
      optional :kind, :string, 2
      optional :version, :string, 3
      optional :server, :string, 4
    end
  end
end

module Pulumirpc
  PluginInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.PluginInfo").msgclass
  PluginDependency = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.PluginDependency").msgclass
end
