# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: resource.proto for package 'pulumirpc'
# Original file comments:
# Copyright 2016-2018, Pulumi Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'grpc'
require 'resource_pb'

module Pulumirpc
  module ResourceMonitor
    # ResourceMonitor is the interface a source uses to talk back to the planning monitor orchestrating the execution.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'pulumirpc.ResourceMonitor'

      rpc :SupportsFeature, ::Pulumirpc::SupportsFeatureRequest, ::Pulumirpc::SupportsFeatureResponse
      rpc :Invoke, ::Pulumirpc::InvokeRequest, ::Pulumirpc::InvokeResponse
      rpc :StreamInvoke, ::Pulumirpc::InvokeRequest, stream(::Pulumirpc::InvokeResponse)
      rpc :Call, ::Pulumirpc::CallRequest, ::Pulumirpc::CallResponse
      rpc :ReadResource, ::Pulumirpc::ReadResourceRequest, ::Pulumirpc::ReadResourceResponse
      rpc :RegisterResource, ::Pulumirpc::RegisterResourceRequest, ::Pulumirpc::RegisterResourceResponse
      rpc :RegisterResourceOutputs, ::Pulumirpc::RegisterResourceOutputsRequest, ::Google::Protobuf::Empty
    end

    Stub = Service.rpc_stub_class
  end
end
