# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resource.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'google/protobuf/struct_pb'
require 'provider_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("resource.proto", :syntax => :proto3) do
    add_message "pulumirpc.SupportsFeatureRequest" do
      optional :id, :string, 1
    end
    add_message "pulumirpc.SupportsFeatureResponse" do
      optional :hasSupport, :bool, 1
    end
    add_message "pulumirpc.ReadResourceRequest" do
      optional :id, :string, 1
      optional :type, :string, 2
      optional :name, :string, 3
      optional :parent, :string, 4
      optional :properties, :message, 5, "google.protobuf.Struct"
      repeated :dependencies, :string, 6
      optional :provider, :string, 7
      optional :version, :string, 8
      optional :acceptSecrets, :bool, 9
      repeated :additionalSecretOutputs, :string, 10
      repeated :aliases, :string, 11
      optional :acceptResources, :bool, 12
    end
    add_message "pulumirpc.ReadResourceResponse" do
      optional :urn, :string, 1
      optional :properties, :message, 2, "google.protobuf.Struct"
    end
    add_message "pulumirpc.RegisterResourceRequest" do
      optional :type, :string, 1
      optional :name, :string, 2
      optional :parent, :string, 3
      optional :custom, :bool, 4
      optional :object, :message, 5, "google.protobuf.Struct"
      optional :protect, :bool, 6
      repeated :dependencies, :string, 7
      optional :provider, :string, 8
      map :propertyDependencies, :string, :message, 9, "pulumirpc.RegisterResourceRequest.PropertyDependencies"
      optional :deleteBeforeReplace, :bool, 10
      optional :version, :string, 11
      repeated :ignoreChanges, :string, 12
      optional :acceptSecrets, :bool, 13
      repeated :additionalSecretOutputs, :string, 14
      repeated :aliases, :string, 15
      optional :importId, :string, 16
      optional :customTimeouts, :message, 17, "pulumirpc.RegisterResourceRequest.CustomTimeouts"
      optional :deleteBeforeReplaceDefined, :bool, 18
      optional :supportsPartialValues, :bool, 19
      optional :remote, :bool, 20
      optional :acceptResources, :bool, 21
      map :providers, :string, :string, 22
      repeated :replaceOnChanges, :string, 23
    end
    add_message "pulumirpc.RegisterResourceRequest.PropertyDependencies" do
      repeated :urns, :string, 1
    end
    add_message "pulumirpc.RegisterResourceRequest.CustomTimeouts" do
      optional :create, :string, 1
      optional :update, :string, 2
      optional :delete, :string, 3
    end
    add_message "pulumirpc.RegisterResourceResponse" do
      optional :urn, :string, 1
      optional :id, :string, 2
      optional :object, :message, 3, "google.protobuf.Struct"
      optional :stable, :bool, 4
      repeated :stables, :string, 5
      map :propertyDependencies, :string, :message, 6, "pulumirpc.RegisterResourceResponse.PropertyDependencies"
    end
    add_message "pulumirpc.RegisterResourceResponse.PropertyDependencies" do
      repeated :urns, :string, 1
    end
    add_message "pulumirpc.RegisterResourceOutputsRequest" do
      optional :urn, :string, 1
      optional :outputs, :message, 2, "google.protobuf.Struct"
    end
  end
end

module Pulumirpc
  SupportsFeatureRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.SupportsFeatureRequest").msgclass
  SupportsFeatureResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.SupportsFeatureResponse").msgclass
  ReadResourceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.ReadResourceRequest").msgclass
  ReadResourceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.ReadResourceResponse").msgclass
  RegisterResourceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.RegisterResourceRequest").msgclass
  RegisterResourceRequest::PropertyDependencies = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.RegisterResourceRequest.PropertyDependencies").msgclass
  RegisterResourceRequest::CustomTimeouts = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.RegisterResourceRequest.CustomTimeouts").msgclass
  RegisterResourceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.RegisterResourceResponse").msgclass
  RegisterResourceResponse::PropertyDependencies = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.RegisterResourceResponse.PropertyDependencies").msgclass
  RegisterResourceOutputsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulumirpc.RegisterResourceOutputsRequest").msgclass
end
